import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    home: "Home",
    services: "Services",
    bookings: "Bookings",
    profile: "Profile",
    customTrip: "Custom Trip",
    dashboard: "Dashboard",
    users: "Users",
    drivers: "Drivers",
    vehicles: "Vehicles",
    routes: "Routes",
    packages: "Packages",
    payments: "Payments",
    reports: "Reports",
    logout: "Logout",
    login: "Login",
    register: "Register",
    welcome: "Welcome",
    cityRide: "City Ride",
    intercityTransfer: "Intercity Transfer",
    tourPackage: "Tour Package",
    customJourney: "Custom Journey",
    quickActions: "Quick Actions",
    bookNow: "Book Now",
    details: "Details",
    verify: "Verify",
    reject: "Reject",
    approve: "Approve",
    save: "Save",
    cancel: "Cancel",
    totalBookings: "Total Bookings",
    pendingPayment: "Pending Payment",
    completedTrips: "Completed Trips",
    totalSpent: "Total Spent",
    whereToGo: "Where would you like to go today?",
    authTitle: "TaxiTrio Booking Platform",
    authSubtitle: "Luxury Transport Services in Cambodia",
    notifications: "Notifications",
    quickRoutes: "Quick Management Routes",
    integrityMonitor: "Live System Integrity Monitor",
    search: "Search...",
    backToBookings: "Back to Bookings",
    driverAvailability: "Live availability states",
    allCaughtUp: "All caught up!",
    schedule: "Schedule",
    earnings: "Earnings",
    history: "Trip History",
    displaySettings: "Display Settings",
    visualTheme: "Visual Theme",
    themeLight: "Black & White",
    themeDark: "Luxury Dark",
    customAccent: "Custom Accent Color",
    presetColors: "Preset Accent Colors",
    fleet: "Fleet",
    privateTours: "Private Tours",
    tours: "Tours",
    intercity: "Intercity",
    corporate: "Corporate",
    support: "Support",
    signIn: "Sign In",
    premiumPlatform: "✨ Premium Travel Platform Cambodia",
    selectJourney: "Select Your Journey",
    homeSubtitle: "Experience reliable transportation tailored to your travel needs across Cambodia.",
    cityRideDesc: "Seamless point-to-point transfers within the city. Perfect for airport transfers, hotel pickups, and local travel.",
    selectCityRide: "Select City Ride",
    intercityDesc: "Travel comfortably between Cambodia’s major destinations with fixed route pricing and reliable drivers.",
    selectIntercity: "Select Intercity",
    tourPackageDesc: "Explore curated destination routes and attraction-based transportation packages across Cambodia.",
    viewPackages: "View Packages",
    customTripDesc: "Design your own itinerary with multiple stops, custom schedules, and flexible transportation needs.",
    buildItinerary: "Build Itinerary",
    vettedDrivers: "100% Vetted Drivers",
    vettedDriversDesc: "Strictly background-checked professional operators.",
    fixedRates: "Fixed Fair Rates",
    fixedRatesDesc: "Transparent route-based pricing without hidden fees.",
    secureBookings: "Secure Bookings",
    secureBookingsDesc: "Instantly track booking status and verify payment proofs.",
    concierge: "24/7 Concierge",
    conciergeDesc: "Premium operator support whenever you travel.",
    footerDesc: "Premium transportation platform connecting travelers with reliable transportation services throughout Cambodia.",
    luxuryFleet: "Luxury Fleet",
    airportTransfers: "Airport Transfers",
    corporateAccounts: "Corporate Accounts",
    contactSupport: "Contact Support",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    copyright: "© 2026 TaxiTrio. All rights reserved.",
    legal: "Legal",
  },
  km: {
    home: "ទំព័រដើម",
    services: "សេវាកម្ម",
    bookings: "ការកក់ទុក",
    profile: "ប្រវត្តិរូប",
    customTrip: "ដំណើរផ្ទាល់ខ្លួន",
    dashboard: "ផ្ទាំងគ្រប់គ្រង",
    users: "អ្នកប្រើប្រាស់",
    drivers: "អ្នកបើកបរ",
    vehicles: "យានយន្ត",
    routes: "ផ្លូវធ្វើដំណើរ",
    packages: "កញ្ចប់ទេសចរណ៍",
    payments: "ការទូទាត់",
    reports: "របាយការណ៍",
    logout: "ចាកចេញ",
    login: "ចូលគណនី",
    register: "ចុះឈ្មោះ",
    welcome: "ស្វាគមន៍",
    cityRide: "ជិះក្នុងក្រុង",
    intercityTransfer: "ធ្វើដំណើរឆ្លងខេត្ត",
    tourPackage: "កញ្ចប់កម្សាន្ត",
    customJourney: "ការធ្វើដំណើរផ្ទាល់ខ្លួន",
    quickActions: "សកម្មភាពរហ័ស",
    bookNow: "កក់ឥឡូវនេះ",
    details: "ព័ត៌មានលម្អិត",
    verify: "ផ្ទៀងផ្ទាត់",
    reject: "បដិសេធ",
    approve: "អនុម័ត",
    save: "រក្សាទុក",
    cancel: "បោះបង់",
    totalBookings: "ការកក់សរុប",
    pendingPayment: "រង់ចាំការបង់ប្រាក់",
    completedTrips: "ដំណើរដែលបានបញ្ចប់",
    totalSpent: "ចំណាយសរុប",
    whereToGo: "តើអ្នកចង់ទៅណាថ្ងៃនេះ?",
    authTitle: "ប្រព័ន្ធកក់យានយន្ត TaxiTrio",
    authSubtitle: "សេវាកម្មដឹកជញ្ជូនលំដាប់ប្រណីតនៅក្នុងប្រទេសកម្ពុជា",
    notifications: "ការជូនដំណឹង",
    quickRoutes: "ផ្លូវគ្រប់គ្រងរហ័ស",
    integrityMonitor: "ការតាមដានសុវត្ថិភាពប្រព័ន្ធបន្តផ្ទាល់",
    search: "ស្វែងរក...",
    backToBookings: "ត្រឡប់ទៅការកក់វិញ",
    driverAvailability: "ស្ថានភាពលទ្ធភាពអ្នកបើកបរផ្ទាល់",
    allCaughtUp: "រួចរាល់ទាំងអស់!",
    schedule: "កាលវិភាគ",
    earnings: "ប្រាក់ចំណូល",
    history: "ប្រវត្តិនៃការធ្វើដំណើរ",
    displaySettings: "ការកំណត់ការបង្ហាញ",
    visualTheme: "រចនាបថកម្មវិធី",
    themeLight: "ស ខ្មៅ",
    themeDark: "ខ្មៅ មាសប្រណីត",
    customAccent: "ពណ៌ចម្រុះផ្ទាល់ខ្លួន",
    presetColors: "ពណ៌ចម្រុះកំណត់ស្រាប់",
    fleet: "ក្រុមរថយន្ត",
    privateTours: "ដំណើរកម្សាន្តឯកជន",
    tours: "ដំណើរកម្សាន្ត",
    intercity: "ឆ្លងខេត្ត",
    corporate: "សាជីវកម្ម",
    support: "គាំទ្រ",
    signIn: "ចូលគណនី",
    premiumPlatform: "✨ ប្រព័ន្ធធ្វើដំណើរលំដាប់ខ្ពស់នៅកម្ពុជា",
    selectJourney: "ជ្រើសរើសការធ្វើដំណើររបស់អ្នក",
    homeSubtitle: "បទពិសោធន៍ដឹកជញ្ជូនគួរឱ្យទុកចិត្ត ស្របតាមតម្រូវការធ្វើដំណើររបស់អ្នកទូទាំងប្រទេសកម្ពុជា។",
    cityRideDesc: "ការផ្ទេរពីចំណុចមួយទៅចំណុចមួយក្នុងទីក្រុងដោយរលូន។ ល្អឥតខ្ចោះសម្រាប់ការផ្ទេរទៅព្រលានយន្តហោះ ការទទួលនៅសណ្ឋាគារ និងការធ្វើដំណើរក្នុងស្រុក។",
    selectCityRide: "ជ្រើសរើសជិះក្នុងក្រុង",
    intercityDesc: "ធ្វើដំណើរប្រកបដោយផាសុកភាពរវាងគោលដៅសំខាន់ៗរបស់កម្ពុជា ជាមួយនឹងតម្លៃផ្លូវថេរ និងអ្នកបើកបរគួរឱ្យទុកចិត្ត។",
    selectIntercity: "ជ្រើសរើសឆ្លងខេត្ត",
    tourPackageDesc: "ស្វែងយល់ពីផ្លូវគោលដៅដែលបានរៀបចំទុកជាមុន និងកញ្ចប់ដឹកជញ្ជូនផ្អែកលើការទាក់ទាញទូទាំងប្រទេសកម្ពុជា។",
    viewPackages: "មើលកញ្ចប់ទេសចរណ៍",
    customTripDesc: "រៀបចំផែនការធ្វើដំណើរផ្ទាល់ខ្លួនរបស់អ្នកជាមួយនឹងការឈប់ច្រើនកន្លែង ពេលវេលាបត់បែន និងតម្រូវការដឹកជញ្ជូនផ្សេងៗ។",
    buildItinerary: "បង្កើតគម្រោងធ្វើដំណើរ",
    vettedDrivers: "អ្នកបើកបរដែលបានត្រួតពិនិត្យ ១០០%",
    vettedDriversDesc: "ប្រតិបត្តិករអាជីពដែលបានត្រួតពិនិត្យប្រវត្តិយ៉ាងតឹងរ៉ឹង។",
    fixedRates: "អត្រាតម្លៃសមរម្យ និងថេរ",
    fixedRatesDesc: "តម្លៃផ្អែកលើផ្លូវធ្វើដំណើរច្បាស់លាស់ ដោយគ្មានថ្លៃលាក់កំបាំង។",
    secureBookings: "ការកក់ប្រកបដោយសុវត្ថិភាព",
    secureBookingsDesc: "តាមដានស្ថានភាពការកក់ភ្លាមៗ និងផ្ទៀងផ្ទីងភស្តុតាងនៃការបង់ប្រាក់។",
    concierge: "សេវាបំរើអតិថិជន ២៤/៧",
    conciergeDesc: "ការគាំទ្រពីប្រតិបត្តិករកម្រិតខ្ពស់នៅរាល់ពេលដែលអ្នកធ្វើដំណើរ។",
    footerDesc: "វេទិកាដឹកជញ្ជូនកម្រិតខ្ពស់ដែលភ្ជាប់អ្នកដំណើរជាមួយសេវាកម្មដឹកជញ្ជូនដែលអាចទុកចិត្តបាននៅទូទាំងប្រទេសកម្ពុជា។",
    luxuryFleet: "ក្រុមរថយន្តទំនើប",
    airportTransfers: "ផ្ទេរទៅព្រលានយន្តហោះ",
    corporateAccounts: "គណនីសាជីវកម្ម",
    contactSupport: "ទាក់ទងផ្នែកគាំទ្រ",
    termsOfService: "លក្ខខណ្ឌប្រើប្រាស់",
    privacyPolicy: "គោលការណ៍ឯកជនភាព",
    copyright: "© ២០២៦ TaxiTrio។ រក្សាសិទ្ធិគ្រប់យ៉ាង។",
    legal: "ផ្លូវច្បាប់",
  },
  zh: {
    home: "首页",
    services: "出行服务",
    bookings: "我的订单",
    profile: "个人资料",
    customTrip: "定制行程",
    dashboard: "控制面板",
    users: "用户管理",
    drivers: "司机管理",
    vehicles: "车辆管理",
    routes: "路线管理",
    packages: "旅游套票",
    payments: "付款审核",
    reports: "系统报告",
    logout: "退出登录",
    login: "登录",
    register: "注册",
    welcome: "欢迎",
    cityRide: "市内单次车",
    intercityTransfer: "城际接送",
    tourPackage: "旅游包车",
    customJourney: "定制旅程",
    quickActions: "快捷操作",
    bookNow: "立即预订",
    details: "详情详情",
    verify: "核对通过",
    reject: "拒绝审核",
    approve: "批准行程",
    save: "保存信息",
    cancel: "取消订单",
    totalBookings: "订单总数",
    pendingPayment: "待付账单",
    completedTrips: "已完行程",
    totalSpent: "消费总计",
    whereToGo: "您今天想去哪里？",
    authTitle: "TaxiTrio 奢华订车服务平台",
    authSubtitle: "柬埔寨卓越奢华商务出行首选",
    notifications: "系统通知",
    quickRoutes: "系统快捷管理导航",
    integrityMonitor: "系统核心健康指标监控",
    search: "搜索...",
    backToBookings: "返回订单列表",
    driverAvailability: "司机在线派遣状态",
    allCaughtUp: "没有任何新消息！",
    schedule: "行程计划",
    earnings: "我的收入",
    history: "行程历史",
    displaySettings: "显示设置",
    visualTheme: "视觉主题",
    themeLight: "黑白极简",
    themeDark: "奢华深金",
    customAccent: "自定义主题色",
    presetColors: "预设主题色",
    fleet: "车队列表",
    privateTours: "私人小团",
    tours: "旅游",
    intercity: "城际专线",
    corporate: "企业服务",
    support: "客服支持",
    signIn: "登录",
    premiumPlatform: "✨ 柬埔寨卓越商务出行平台",
    selectJourney: "选择您的旅程",
    homeSubtitle: "为您在柬埔寨全境提供最卓越、安全、量身定制的出行体验。",
    cityRideDesc: "市内便捷的点对点接送服务。非常适合机场接送、酒店迎送及市区日常出行。",
    selectCityRide: "选择市内单次车",
    intercityDesc: "在柬埔寨各大城市之间舒适旅行，享受固定路线的透明定价和经验丰富的专业司机。",
    selectIntercity: "选择城际专线",
    tourPackageDesc: "探索精心设计的特色景点和旅游包车路线，饱览柬埔寨名胜风光。",
    viewPackages: "查看包车套票",
    customTripDesc: "自由定制您的专属行程，包含多点停留、弹性时间表和个性化的车型需求。",
    buildItinerary: "定制专属行程",
    vettedDrivers: "100% 严审司机",
    vettedDriversDesc: "所有专业司机均经过严格的背景安全审查。",
    fixedRates: "固定透明票价",
    fixedRatesDesc: "路线计费一目了然，杜绝任何隐性收费。",
    secureBookings: "安全放心预订",
    secureBookingsDesc: "实时追踪您的订单状态，便捷验证付款凭证。",
    concierge: "24/7 全天候管家",
    conciergeDesc: "专属人工客服时刻为您在线保驾护航。",
    footerDesc: "连接旅客与柬埔寨全国可靠交通服务的优质运输平台。",
    luxuryFleet: "奢华车队",
    airportTransfers: "机场接送",
    corporateAccounts: "企业账户",
    contactSupport: "联络客服",
    termsOfService: "服务条款",
    privacyPolicy: "隐私政策",
    copyright: "© 2026 TaxiTrio. 保留所有权利。",
    legal: "法律声明",
  },
  ko: {
    home: "홈",
    services: "이용 서비스",
    bookings: "예약 내역",
    profile: "프로필",
    customTrip: "맞춤 여행",
    dashboard: "대시보드",
    users: "사용자 관리",
    drivers: "드라이버 관리",
    vehicles: "차량 관리",
    routes: "노선 관리",
    packages: "패키지 상품",
    payments: "결제 관리",
    reports: "분석 보고서",
    logout: "로그아웃",
    login: "로그인",
    register: "회원가입",
    welcome: "환영합니다",
    cityRide: "시내 승차",
    intercityTransfer: "도시 간 이동",
    tourPackage: "투어 패키지",
    customJourney: "맞춤형 여행",
    quickActions: "빠른 메뉴",
    bookNow: "지금 예약",
    details: "상세 보기",
    verify: "결제 확인",
    reject: "반려 처리",
    approve: "승인 완료",
    save: "저장 하기",
    cancel: "예약 취소",
    totalBookings: "총 예약 건수",
    pendingPayment: "결제 대기중",
    completedTrips: "운행 완료",
    totalSpent: "총 지출액",
    whereToGo: "오늘 어디로 모실까요?",
    authTitle: "TaxiTrio 럭셔리 모빌리티 플랫폼",
    authSubtitle: "캄보디아 프리미엄 의전 차량 서비스",
    notifications: "알림 센터",
    quickRoutes: "관리자 바로가기 메뉴",
    integrityMonitor: "실시간 서버 무결성 모니터링",
    search: "검색...",
    backToBookings: "예약 목록으로 돌아가기",
    driverAvailability: "드라이버 배치 가용성 상태",
    allCaughtUp: "모든 알림을 확인했습니다!",
    schedule: "운행 일정",
    earnings: "내 수입",
    history: "운행 기록",
    displaySettings: "화면 설정",
    visualTheme: "화면 모드",
    themeLight: "블랙 & 화이트",
    themeDark: "다크 골드",
    customAccent: "사용자 정의 강조색",
    presetColors: "기본 강조색",
    fleet: "차량 목록",
    privateTours: "프라이빗 투어",
    tours: "투어",
    intercity: "도시 간 이동",
    corporate: "비즈니스",
    support: "고객 지원",
    signIn: "로그인",
    premiumPlatform: "✨ 캄보디아 프리미엄 모빌리티 서비스",
    selectJourney: "여정을 선택하세요",
    homeSubtitle: "캄보디아 전역에서 고객님의 필요에 맞춘 안전하고 신뢰할 수 있는 이동 서비스를 제공합니다.",
    cityRideDesc: "시내 구간을 이동하는 편리한 포인트 투 포인트 서비스입니다. 공항 픽업/샌딩, 호텔 이동 등에 적합합니다.",
    selectCityRide: "시내 승차 선택",
    intercityDesc: "캄보디아 주요 도시 간을 고정된 투명한 요금으로 베테랑 드라이버와 함께 안락하게 이동하세요.",
    selectIntercity: "도시 간 이동 선택",
    tourPackageDesc: "캄보디아 전역의 엄선된 관광 코스와 명소를 포함한 맞춤형 교통 패키지를 확인해보세요.",
    viewPackages: "투어 패키지 보기",
    customTripDesc: "여러 경유지, 자유로운 일정 설정, 승하차 시간 등 나만의 특별한 여행 경로를 설계하세요.",
    buildItinerary: "나만의 맞춤 경로 제작",
    vettedDrivers: "100% 신원 보증 드라이버",
    vettedDriversDesc: "엄격한 신원 검증과 배경 조사를 통과한 프로 드라이버만 배치됩니다.",
    fixedRates: "고정 정찰제 요금",
    fixedRatesDesc: "경로 기반의 투명한 요금 책정으로 추가 요금 요구가 없습니다.",
    secureBookings: "안전한 예약 관리",
    secureBookingsDesc: "실시간으로 예약 상태를 조회하고 결제 영수증을 신속하게 검증합니다.",
    concierge: "24/7 연중무휴 상담",
    conciergeDesc: "이용 시 언제든 즉시 응대하는 프리미엄 어시스턴트 서비스를 지원합니다.",
    footerDesc: "캄보디아 전역의 신뢰할 수 있는 교통 서비스와 여행자를 연결하는 프리미엄 교통 플랫폼.",
    luxuryFleet: "럭셔리 차량",
    airportTransfers: "공항 픽업/샌딩",
    corporateAccounts: "법인 회원",
    contactSupport: "고객센터 문의",
    termsOfService: "이용 약관",
    privacyPolicy: "개인정보 처리방침",
    copyright: "© 2026 TaxiTrio. All rights reserved.",
    legal: "법적 고지",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [locale, setLocale] = useState('en');

  useEffect(() => {
    const saved = localStorage.getItem('taxi-trio-locale');
    if (saved && translations[saved]) {
      setLocale(saved);
    }
  }, []);

  const changeLocale = (newLocale) => {
    if (translations[newLocale]) {
      setLocale(newLocale);
      localStorage.setItem('taxi-trio-locale', newLocale);
    }
  };

  const t = (key, fallback = '') => {
    return translations[locale]?.[key] || translations['en']?.[key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, changeLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  return useContext(LanguageContext);
}
