import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    home: "Home",
    services: "Services",
    bookings: "Bookings",
    profile: "Profile",
    customTrip: "Custom Trip",
    dashboard: "Dashboard",
    users: "Users",
    drivers: "Drivers",
    vehicles: "Vehicles",
    routes: "Routes",
    packages: "Packages",
    payments: "Payments",
    reports: "Reports",
    logout: "Logout",
    login: "Login",
    register: "Register",
    welcome: "Welcome",
    cityRide: "City Ride",
    intercityTransfer: "Intercity Transfer",
    tourPackage: "Tour Package",
    customJourney: "Custom Journey",
    quickActions: "Quick Actions",
    bookNow: "Book Now",
    details: "Details",
    verify: "Verify",
    reject: "Reject",
    approve: "Approve",
    save: "Save",
    cancel: "Cancel",
    totalBookings: "Total Bookings",
    pendingPayment: "Pending Payment",
    completedTrips: "Completed Trips",
    totalSpent: "Total Spent",
    whereToGo: "Where would you like to go today?",
    authTitle: "TaxiTrio Booking Platform",
    authSubtitle: "Luxury Transport Services in Cambodia",
    notifications: "Notifications",
    quickRoutes: "Quick Management Routes",
    integrityMonitor: "Live System Integrity Monitor",
    search: "Search...",
    backToBookings: "Back to Bookings",
    driverAvailability: "Live availability states",
    allCaughtUp: "All caught up!",
    schedule: "Schedule",
    earnings: "Earnings",
    history: "Trip History",
    displaySettings: "Display Settings",
    visualTheme: "Visual Theme",
    themeLight: "Black & White",
    themeDark: "Luxury Dark",
    customAccent: "Custom Accent Color",
    presetColors: "Preset Accent Colors",
  },
  km: {
    home: "ទំព័រដើម",
    services: "សេវាកម្ម",
    bookings: "ការកក់ទុក",
    profile: "ប្រវត្តិរូប",
    customTrip: "ដំណើរផ្ទាល់ខ្លួន",
    dashboard: "ផ្ទាំងគ្រប់គ្រង",
    users: "អ្នកប្រើប្រាស់",
    drivers: "អ្នកបើកបរ",
    vehicles: "យានយន្ត",
    routes: "ផ្លូវធ្វើដំណើរ",
    packages: "កញ្ចប់ទេសចរណ៍",
    payments: "ការទូទាត់",
    reports: "របាយការណ៍",
    logout: "ចាកចេញ",
    login: "ចូលគណនី",
    register: "ចុះឈ្មោះ",
    welcome: "ស្វាគមន៍",
    cityRide: "ជិះក្នុងក្រុង",
    intercityTransfer: "ធ្វើដំណើរឆ្លងខេត្ត",
    tourPackage: "កញ្ចប់កម្សាន្ត",
    customJourney: "ការធ្វើដំណើរផ្ទាល់ខ្លួន",
    quickActions: "សកម្មភាពរហ័ស",
    bookNow: "កក់ឥឡូវនេះ",
    details: "ព័ត៌មានលម្អិត",
    verify: "ផ្ទៀងផ្ទាត់",
    reject: "បដិសេធ",
    approve: "អនុម័ត",
    save: "រក្សាទុក",
    cancel: "បោះបង់",
    totalBookings: "ការកក់សរុប",
    pendingPayment: "រង់ចាំការបង់ប្រាក់",
    completedTrips: "ដំណើរដែលបានបញ្ចប់",
    totalSpent: "ចំណាយសរុប",
    whereToGo: "តើអ្នកចង់ទៅណាថ្ងៃនេះ?",
    authTitle: "ប្រព័ន្ធកក់យានយន្ត TaxiTrio",
    authSubtitle: "សេវាកម្មដឹកជញ្ជូនលំដាប់ប្រណីតនៅក្នុងប្រទេសកម្ពុជា",
    notifications: "ការជូនដំណឹង",
    quickRoutes: "ផ្លូវគ្រប់គ្រងរហ័ស",
    integrityMonitor: "ការតាមដានសុវត្ថិភាពប្រព័ន្ធបន្តផ្ទាល់",
    search: "ស្វែងរក...",
    backToBookings: "ត្រឡប់ទៅការកក់វិញ",
    driverAvailability: "ស្ថានភាពលទ្ធភាពអ្នកបើកបរផ្ទាល់",
    allCaughtUp: "រួចរាល់ទាំងអស់!",
    schedule: "កាលវិភាគ",
    earnings: "ប្រាក់ចំណូល",
    history: "ប្រវត្តិនៃការធ្វើដំណើរ",
    displaySettings: "ការកំណត់ការបង្ហាញ",
    visualTheme: "រចនាបថកម្មវិធី",
    themeLight: "ស ខ្មៅ",
    themeDark: "ខ្មៅ មាសប្រណីត",
    customAccent: "ពណ៌ចម្រុះផ្ទាល់ខ្លួន",
    presetColors: "ពណ៌ចម្រុះកំណត់ស្រាប់",
  },
  zh: {
    home: "首页",
    services: "出行服务",
    bookings: "我的订单",
    profile: "个人资料",
    customTrip: "定制行程",
    dashboard: "控制面板",
    users: "用户管理",
    drivers: "司机管理",
    vehicles: "车辆管理",
    routes: "路线管理",
    packages: "旅游套票",
    payments: "付款审核",
    reports: "系统报告",
    logout: "退出登录",
    login: "登录",
    register: "注册",
    welcome: "欢迎",
    cityRide: "市内单次车",
    intercityTransfer: "城际接送",
    tourPackage: "旅游包车",
    customJourney: "定制旅程",
    quickActions: "快捷操作",
    bookNow: "立即预订",
    details: "详情详情",
    verify: "核对通过",
    reject: "拒绝审核",
    approve: "批准行程",
    save: "保存信息",
    cancel: "取消订单",
    totalBookings: "订单总数",
    pendingPayment: "待付账单",
    completedTrips: "已完行程",
    totalSpent: "消费总计",
    whereToGo: "您今天想去哪里？",
    authTitle: "TaxiTrio 奢华订车服务平台",
    authSubtitle: "柬埔寨卓越奢华商务出行首选",
    notifications: "系统通知",
    quickRoutes: "系统快捷管理导航",
    integrityMonitor: "系统核心健康指标监控",
    search: "搜索...",
    backToBookings: "返回订单列表",
    driverAvailability: "司机在线派遣状态",
    allCaughtUp: "没有任何新消息！",
    schedule: "行程计划",
    earnings: "我的收入",
    history: "行程历史",
    displaySettings: "显示设置",
    visualTheme: "视觉主题",
    themeLight: "黑白极简",
    themeDark: "奢华深金",
    customAccent: "自定义主题色",
    presetColors: "预设主题色",
  },
  ko: {
    home: "홈",
    services: "이용 서비스",
    bookings: "예약 내역",
    profile: "프로필",
    customTrip: "맞춤 여행",
    dashboard: "대시보드",
    users: "사용자 관리",
    drivers: "드라이버 관리",
    vehicles: "차량 관리",
    routes: "노선 관리",
    packages: "패키지 상품",
    payments: "결제 관리",
    reports: "분석 보고서",
    logout: "로그아웃",
    login: "로그인",
    register: "회원가입",
    welcome: "환영합니다",
    cityRide: "시내 승차",
    intercityTransfer: "도시 간 이동",
    tourPackage: "투어 패키지",
    customJourney: "맞춤형 여행",
    quickActions: "빠른 메뉴",
    bookNow: "지금 예약",
    details: "상세 보기",
    verify: "결제 확인",
    reject: "반려 처리",
    approve: "승인 완료",
    save: "저장 하기",
    cancel: "예약 취소",
    totalBookings: "총 예약 건수",
    pendingPayment: "결제 대기중",
    completedTrips: "운행 완료",
    totalSpent: "총 지출액",
    whereToGo: "오늘 어디로 모실까요?",
    authTitle: "TaxiTrio 럭셔리 모빌리티 플랫폼",
    authSubtitle: "캄보디아 프리미엄 의전 차량 서비스",
    notifications: "알림 센터",
    quickRoutes: "관리자 바로가기 메뉴",
    integrityMonitor: "실시간 서버 무결성 모니터링",
    search: "검색...",
    backToBookings: "예약 목록으로 돌아가기",
    driverAvailability: "드라이버 배치 가용성 상태",
    allCaughtUp: "모든 알림을 확인했습니다!",
    schedule: "운행 일정",
    earnings: "내 수입",
    history: "운행 기록",
    displaySettings: "화면 설정",
    visualTheme: "화면 모드",
    themeLight: "블랙 & 화이트",
    themeDark: "다크 골드",
    customAccent: "사용자 정의 강조색",
    presetColors: "기본 강조색",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [locale, setLocale] = useState('en');

  useEffect(() => {
    const saved = localStorage.getItem('taxi-trio-locale');
    if (saved && translations[saved]) {
      setLocale(saved);
    }
  }, []);

  const changeLocale = (newLocale) => {
    if (translations[newLocale]) {
      setLocale(newLocale);
      localStorage.setItem('taxi-trio-locale', newLocale);
    }
  };

  const t = (key, fallback = '') => {
    return translations[locale]?.[key] || translations['en']?.[key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, changeLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  return useContext(LanguageContext);
}
